# Generated by Django 5.1.15 on 2026-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('AUXILIAR', 'Auxiliar')], default='AUXILIAR', max_length=20, verbose_name='Perfil/Cargo'),
        ),
    ]
