# Generated by Django 5.1.15 on 2026-03-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_usuariocustomizado_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador de Sistema'), ('GESTOR', 'Gestor'), ('VENDEDOR', 'Vendedor'), ('OPERADOR', 'Operador (Executor)')], default='GESTOR', max_length=20, verbose_name='Perfil/Cargo'),
        ),
    ]
