# Generated by Django 5.1.15 on 2026-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_alter_usuariocustomizado_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo da Empresa')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Dados da Empresa',
                'verbose_name_plural': 'Dados da Empresa',
            },
        ),
    ]
