# Generated by Django 5.1.15 on 2026-03-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=200, verbose_name='Nome Fantasia / Marca'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social / Nome Completo'),
        ),
    ]
