# Generated by Django 5.0.6 on 2026-03-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_remove_empresa_cnpj_empresa_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='configuracoes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Módulos e Configurações'),
        ),
    ]
