# Generated by Django 5.1.15 on 2026-03-01 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0006_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato/Telefone')),
                ('categoria', models.CharField(choices=[('REVELACAO', 'Revelação de Fotos'), ('ALBUNS', 'Álbuns e Fotolivros'), ('CAIXAS', 'Caixas Personalizadas'), ('EQUIPAMENTO', 'Equipamentos e Manutenção'), ('TRANSPORTE', 'Transporte e Logística'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa')),
                ('pago', models.BooleanField(default=True, verbose_name='Status de Pagamento (Pago?)')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='contratos.contrato', verbose_name='Contrato Vinculado')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos', to='financeiro.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Custo/Despesa',
                'verbose_name_plural': 'Custos e Despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SAIDA', 'Saída (-)')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('PAGAMENTO_CLIENTE', 'Recebimento de Contrato'), ('PAGAMENTO_FORNECEDOR', 'Pagamento de Fornecedor'), ('TRANSPORTE', 'Transporte/Combustível'), ('MARKETING', 'Marketing e Divulgação'), ('ALUGUEL', 'Aluguel/Estúdio'), ('DIVERSOS', 'Diversos')], default='DIVERSOS', max_length=30, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('custo_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacao', to='financeiro.custo', verbose_name='Referência de Custo')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Fluxo de Caixa',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
