# Generated by Django 5.1.15 on 2026-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaocaixa',
            name='tipo_receita',
            field=models.CharField(blank=True, choices=[('SERVICO', 'Prestação de Serviços'), ('PRODUTO', 'Revenda de Mercadorias')], default='SERVICO', max_length=10, null=True, verbose_name='Tipo de Receita (MEI)'),
        ),
    ]
