# Generated by Django 5.1.15 on 2026-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='template_texto',
            field=models.TextField(blank=True, help_text='Use variáveis como {{cliente}}, {{valor}}, {{data}} para personalizar.', null=True, verbose_name='Texto Base para Orçamento'),
        ),
    ]
