# Generated by Django 5.0.6 on 2026-03-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_tipo_pessoa_alter_cliente_documento'),
        ('contratos', '0008_pagamento_orcamento_alter_pagamento_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncomendaSurf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=50, verbose_name='Peso')),
                ('altura', models.CharField(max_length=50, verbose_name='Altura')),
                ('tipo_prancha', models.CharField(choices=[('SHORTBOARD', 'Shortboard (Pranchinha)'), ('FISH', 'Fish'), ('LONGBOARD', 'Longboard'), ('FAN_BOARD', 'Fan Board'), ('STAND_UP', 'Stand Up')], max_length=20, verbose_name='Tipo de Prancha')),
                ('quilhas', models.CharField(choices=[('TRI', 'Triquilhas (Convencional)'), ('BI', 'Biquilha'), ('QUADRI', 'Quadriquilha'), ('MULTI', 'Multiquilha (Tri ou Quadri)')], max_length=10, verbose_name='Quilhas')),
                ('tipo_fundo', models.CharField(choices=[('FLAT', 'Flat'), ('CONCAVE', 'Concave'), ('DOUBLE_CONCAVE', 'Double Concave'), ('THREE_CONCAVE', 'Three Concave'), ('CANALETA_CENTRAL', 'Canaleta - Centralizada'), ('CANALETA_QUILHAS', 'Canaleta - Entre Quilhas')], max_length=20, verbose_name='Tipo de Fundo')),
                ('rabeta', models.CharField(choices=[('PIN', 'Pin'), ('ROUND', 'Round'), ('SQUARE', 'Square'), ('SQUASH', 'Squash'), ('KING_SCRON', 'King Scron'), ('DIMON', 'Dimon'), ('SWALLOW', 'Swallow'), ('HALF_MOON', 'Half Moon Tail'), ('WING', 'Wing'), ('DOUBLE_WING', 'Double Wing'), ('ROUND_SQUASH', 'Round Squash')], max_length=20, verbose_name='Rabeta')),
                ('tamanho', models.CharField(max_length=50, verbose_name='Tamanho da Prancha')),
                ('modelo_especifico', models.CharField(blank=True, choices=[('INICIANTE', 'Iniciante'), ('ESCOLINHA', 'Escolinha'), ('SEMI_PROGRESSIVO', 'Semi-Progressivo'), ('REMADA', 'Remada'), ('INTERMEDIARIO', 'Intermediário'), ('SURF', 'Surf'), ('CLASSICO', 'Clássico'), ('PROGRESSIVO', 'Progressivo')], max_length=20, null=True)),
                ('bordas', models.CharField(choices=[('FINA', 'Borda Fina'), ('MEDIA', 'Borda Média'), ('GROSSA', 'Borda Grossa')], max_length=10, verbose_name='Bordas')),
                ('tipo_laminacao', models.CharField(choices=[('FORTE', 'Forte (Mais Pesada)'), ('NORMAL', 'Normal'), ('COMPETICAO', 'Competição'), ('POLIDA', 'Polida')], max_length=20, verbose_name='Tipo de Laminação')),
                ('copinho', models.CharField(choices=[('FUSION', 'Fusion'), ('FCS2', 'FCS-II'), ('FUTURE', 'Future Fins')], max_length=10, verbose_name='Tipo de Copinho')),
                ('pintura_desejada', models.BooleanField(default=False, verbose_name='Deseja Pintura?')),
                ('tipo_pintura', models.CharField(blank=True, choices=[('SIMPLES_FUNDO', 'Simples - Apenas Fundo'), ('SIMPLES_BORDAS', 'Simples - Apenas Bordas'), ('SIMPLES_DECK', 'Simples - Deck'), ('SIMPLES_FUNDO_DECK', 'Simples - Fundo e Deck'), ('ARTISTICA', 'Pintura Artística (Abstrato/Complexo)')], max_length=20, null=True)),
                ('quantidade_cores', models.CharField(blank=True, choices=[('1', 'Uma Cor'), ('2', 'Duas Cores'), ('3', 'Três Cores'), ('4+', 'Mais que Três')], max_length=5, null=True)),
                ('link_imagem_pintura', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Imagem')),
                ('pintura_arquivo', models.FileField(blank=True, null=True, upload_to='encomendas/pinturas/', verbose_name='Desenho da Pintura (Anexo)')),
                ('shape_3d_arquivo', models.FileField(blank=True, null=True, upload_to='encomendas/shapes_3d/', verbose_name='Projeto Shape 3D')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas_surf', to='clientes.cliente')),
                ('contrato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_surf', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Encomenda de Prancha',
                'verbose_name_plural': 'Encomendas de Pranchas',
            },
        ),
    ]
