# Generated by Django 5.0.6 on 2026-03-03 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomendasurf',
            name='data_encomenda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Encomenda'),
        ),
        migrations.AddField(
            model_name='encomendasurf',
            name='data_previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='encomendasurf',
            name='status',
            field=models.CharField(choices=[('FILA', 'Em Fila'), ('PRODUCAO', 'Em Produção'), ('FINALIZADA', 'Finalizada'), ('ENTREGUE', 'Entregue')], default='FILA', max_length=20, verbose_name='Status da Encomenda'),
        ),
    ]
