# Generated by Django 5.0.6 on 2026-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0002_encomendasurf_data_encomenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomendasurf',
            name='valor_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Entrada'),
        ),
        migrations.AddField(
            model_name='encomendasurf',
            name='valor_restante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Restante'),
        ),
        migrations.AddField(
            model_name='encomendasurf',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
