# Generated by Django 5.0.6 on 2026-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0003_encomendasurf_valor_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomendasurf',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AddField(
            model_name='encomendasurf',
            name='venda_lancada',
            field=models.BooleanField(default=False, verbose_name='Venda Lançada no Financeiro'),
        ),
    ]
