# Generated by Django 5.1.15 on 2026-02-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
