# Generated by Django 5.1.15 on 2026-02-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final (R$)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('termos', models.TextField(blank=True, null=True, verbose_name='Termos do Contrato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
                ('servicos', models.ManyToManyField(related_name='contratos', to='servicos.servico', verbose_name='Serviços Contratados')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
