# Generated by Django 5.1.15 on 2026-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_hora_evento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Evento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status do Contrato'),
        ),
    ]
