# Generated by Django 5.1.15 on 2026-03-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_data_hora_evento_contrato_status_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='condicao_pagamento',
            field=models.CharField(choices=[('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão')], default='A_VISTA', max_length=20, verbose_name='Condição de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='Data do Contrato'),
        ),
    ]
