# Generated by Django 5.1.15 on 2026-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_condicao_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='condicao_pagamento',
            field=models.CharField(choices=[('A_VISTA', 'À Vista'), ('PARCELADO', 'Parcelado'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão')], default='A_VISTA', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Condição de Pagamento'),
        ),
    ]
