# Generated by Django 5.1.15 on 2026-03-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_condicao_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arquivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/assinados/', verbose_name='Contrato Assinado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Entrada (R$)'),
        ),
    ]
