# Generated by Django 5.1.15 on 2026-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo_desconto',
            field=models.CharField(choices=[('VALOR', 'R$'), ('PERCENTUAL', '%')], default='VALOR', max_length=20, verbose_name='Tipo de Desconto'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Bruto (R$)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final Acordado (R$)'),
        ),
    ]
