# Generated by Django 5.1.15 on 2026-03-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_contrato_tipo_desconto_contrato_valor_bruto_and_more'),
        ('orcamentos', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='orcamentos.orcamento', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contratos.contrato', verbose_name='Contrato'),
        ),
    ]
