# Generated by Django 5.0.6 on 2026-03-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_pagamento_orcamento_alter_pagamento_contrato'),
        ('encomendas', '0004_encomendasurf_data_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='encomenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='encomendas.encomendasurf', verbose_name='Encomenda'),
        ),
    ]
